### ISSUE TITLE
html formatting

### ISSUE THREAD

**Issue by nathanallen** [ivannash23/twoAmigos#5]
Warning: Prefer css styling to html markup tag `large` in this context.
From line 23, column 35; to line 23, column 41
`t-center"><large>CarShi`

Error: Missing space between attributes.
At line 50, column 32
`m id="raceGame"class="text-rig`

Warning: Element h3 not allowed as child of element ul.
From line 59, column 28; to line 59, column 31
`coreList"><h3>Recent`

**Comment by chri-roch12** [comment]
Html has been updated with these changes, and css was added to take the place of the html markup styling.
